<?php

// $Id$

/**
 * Converts the per-content-type variables used in the 4.6.x version
 *  into the ones expected by the 4.7.x version.
 */
function signup_ecommerce_update_4700() {
  $query = db_query("SELECT * FROM {variable} v WHERE v.name LIKE 'signup_ecommerce_nodeapi_%' ORDER BY v.name");
  while ($fetch = db_fetch_object($query)) {
    $type = substr($fetch->name, 25);
    variable_set('signup_ecommerce_'. $type, $fetch->value);
    variable_del($fetch->name);
  }
}

